### ISSUE TITLE
Expand testing suite

### ISSUE THREAD

**Issue by jimboid** [jimboid/aiida-gromacs#23]
This should include:

- [x] #28
- [x] Tests for parsers
- [x] #36
- [x] Tests for data
- [x] #25
- [x] Tests for export functions

**Comment by jkalayan** [comment]
Tests for current parsers are already incorporated in tests for calcs, so we can wait to write tests until we create more complex file parsers

**Comment by jimboid** [comment]
Most of the export functions are covered in other tests. We can expand this in future.
